name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROD_PROJECT_ID }}

on:
  push:
    branches:
      - prod

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        working-directory: webapp
        run: npm install --global vercel

      - name: Pull Vercel Info from environment variables
        working-directory: webapp
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: webapp
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        working-directory: webapp
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}